#!/usr/bin/with-contenv bash

# create folders
mkdir -p "${APP_ROOT}"
mkdir -p "${CONFIG}"
mkdir -p /var/log/couchpotato
#maybe should do /mnt and newgroup /folders, but too tired

# install app
if [[ -d "${APP_ROOT}/${APPDIRNAME}/.git" ]]
then
    cd "${APP_ROOT}/${APPDIRNAME}"
    git stash
    git checkout ${GITBRANCH}
    git pull
else
    git clone ${GITURL} "${APP_ROOT}/${APPDIRNAME}" -b $GITBRANCH
fi

if [[ -d "${APP_ROOT}/CP-BackupTool/.git" ]]
then
    cd "${APP_ROOT}/CP-BackupTool"
    git stash
    git pull
else
    git clone https://github.com/clinton-hall/CP-BackupTool.git "${APP_ROOT}/CP-BackupTool"
fi

# permissions
chown -R abc:abc "${APP_ROOT}"
chown -R abc:abc "${CONFIG}"
chmod 777 /var/log/couchpotato
